#############################
#   APDO. RUTAS GENÃ‰RICAS   #
#############################

changeLanguage:
    pattern: /lang/{lang}
    defaults: { _controller: UtilBundle:Generic:changeLanguage }
    
###########################
#   APDO. AJAX   #
###########################
user_provinces: 
    pattern: /provincesFromRegion
    defaults: { _controller: UtilBundle:Default:provincesFromRegion }